-- Script de criação das tabelas.
CREATE TABLE USUARIO(
	ID INTEGER,
	NOME VARCHAR(100) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	GENERO VARCHAR(100),
	PRIMARY KEY(ID)
);

CREATE TABLE ARTISTA(
	ID_ARTISTA INTEGER,
	BIOGRAFIA TEXT,
	PRIMARY KEY(ID_ARTISTA)
);

CREATE TABLE MUSICA(
	ID_MUSICA INTEGER,
	TITULO VARCHAR(100) NOT NULL,
	--GENERO_MUSICAL VARCHAR(30) NOT NULL,
	DATA_LANCAMENTO DATE NOT NULL,
	ID_ALBUM INTEGER,
	PRIMARY KEY(ID_MUSICA)
);

CREATE TABLE ALBUM(
	ID_ALBUM INTEGER,
	TITULO VARCHAR(100) UNIQUE NOT NULL,
	DATA_LANCAMENTO DATE NOT NULL,
	ID_CRIADOR INTEGER,
	--GENERO_MUSICAL VARCHAR(30) NOT NULL,
	PRIMARY KEY (ID_ALBUM)
);

CREATE TABLE HISTORICO_REPRODUCAO (
    ID_REPRODUCAO SERIAL,
    ID_MUSICA INT,
	ID_USUARIO INT,
    DATA_HORA TIMESTAMP NOT NULL,
    DISPOSITIVO VARCHAR(100),
    PRIMARY KEY (ID_REPRODUCAO)
);

CREATE TABLE PLAYLIST(
	ID_PLAYLIST INTEGER,
	TITULO VARCHAR(100) NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	ID_CRIADOR INTEGER,
	PRIMARY KEY(ID_PLAYLIST)
);

CREATE TABLE GENERO_MUSICAL (
    ID_GENERO INTEGER,
    NOME_GENERO VARCHAR(30) UNIQUE NOT NULL,
	PRIMARY KEY (ID_GENERO)
);

CREATE TABLE ARTISTA_MUSICAS(
	ID_ARTISTA INTEGER,
	ID_MUSICA INTEGER,
	PRIMARY KEY(ID_ARTISTA , ID_MUSICA)
);

CREATE TABLE PLAYLIST_MUSICAS(
	ID_PLAYLIST INTEGER,
	ID_MUSICA INTEGER,
	PRIMARY KEY(ID_PLAYLIST , ID_MUSICA)
);

CREATE TABLE GENERO_DA_MUSICA(
	ID_GENERO INTEGER,
	ID_MUSICA INTEGER,
	PRIMARY KEY (ID_GENERO, ID_MUSICA)
);

CREATE TABLE GENERO_DO_ALBUM(
	ID_GENERO INTEGER,
	ID_ALBUM INTEGER,
	PRIMARY KEY (ID_GENERO, ID_ALBUM)
);

--RELAÇÃO DE HERANÇA ENTRE ARTISTA E USUARIO;
ALTER TABLE ARTISTA
ADD CONSTRAINT FK_ARTISTA_USUARIO FOREIGN KEY(ID_ARTISTA) REFERENCES USUARIO(ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

-- CHAVE ESTRANGEIRA PARA O ID DO CRIADOR;
ALTER TABLE PLAYLIST
ADD CONSTRAINT FK_USUARIO_PLAYLIST FOREIGN KEY(ID_CRIADOR) REFERENCES USUARIO(ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

--RELACIONA VARIAS MUSICAS A UMA PLAYLIST E UMA MUSICA PODE ESTRA PRESENTE EM PLAYLISTS DIFERENTES
ALTER TABLE PLAYLIST_MUSICAS
ADD CONSTRAINT FK_PLAYLIST_PM FOREIGN KEY(ID_PLAYLIST) REFERENCES PLAYLIST(ID_PLAYLIST),
ADD CONSTRAINT FK_MUSICA_PM FOREIGN KEY(ID_MUSICA) REFERENCES MUSICA(ID_MUSICA)
ON UPDATE RESTRICT
ON DELETE RESTRICT;

--CHAVE ESTRANGEIRA PARA O ID DO USUARIO QUE REPRODUZIU A MUSICA;
ALTER TABLE HISTORICO_REPRODUCAO
ADD CONSTRAINT FK_USUARIO_HIST FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID)
ON UPDATE CASCADE
ON DELETE CASCADE;

--CHAVE ESTRANGEIRA PARA O ID DO CRIADOR DA MUSICA
ALTER TABLE MUSICA
ADD CONSTRAINT FK_MUSICA_ARTISTA FOREIGN KEY(ID_ARTISTA) REFERENCES ARTISTA(ID_ARTISTA)
ON UPDATE CASCADE
ON DELETE RESTRICT;

-- ASSOCIA UMA MUSICA A UM OU MAIS ARTISTA E UM ARTISTA A VARIAS MUSICAS;
ALTER TABLE ARTISTA_MUSICAS
ADD CONSTRAINT FK_ARTISTA_AM FOREIGN KEY(ID_ARTISTA) REFERENCES ARTISTA(ID_ARTISTA),
ADD CONSTRAINT FK_MUSICA_AM FOREIGN KEY(ID_MUSICA) REFERENCES MUSICA(ID_MUSICA)
ON UPDATE RESTRICT
ON DELETE RESTRICT;

-- RELACIONA O ALBUM AO SEU CRIADOR(CORRIGIR: referência deveria ser para artista)
ALTER TABLE ALBUM
ADD CONSTRAINT FK_CRIADOR FOREIGN KEY(ID_CRIADOR) REFERENCES USUARIO(ID)
ON UPDATE CASCADE
ON DELETE RESTRICT;

-- ASSOCIA A MUSICA AO HISTORICO

ALTER TABLE HISTORICO_REPRODUCAO
ADD CONSTRAINT FK_MUSICA_HIST FOREIGN KEY(ID_MUSICA) REFERENCES MUSICA(ID_MUSICA)
ON UPDATE CASCADE
ON DELETE CASCADE;

--ASSOCIA A MUSICA A O SEU RESPECTIVO ALBUM
ALTER TABLE MUSICA
ADD CONSTRAINT FK_ALBUM_MUSICA FOREIGN KEY(ID_ALBUM) REFERENCES ALBUM(ID_ALBUM)
ON UPDATE CASCADE
ON DELETE CASCADE;

-- RELACIONA MUSICA AOS GENEROS MUSICAIS, UMA MUSICA PODE TER MAIS DE UM GENERO MUSICAL,
--ENTÃO O ATRIBUTO MULTIVALORADO VAI SER REPRESENTADO COMO UMA TABELA ASSOCIATIVA.
ALTER TABLE GENERO_DA_MUSICA
ADD CONSTRAINT FK_GENERO_GM FOREIGN KEY(ID_GENERO) REFERENCES GENERO_MUSICAL(ID_GENERO),
ADD CONSTRAINT FK_MUSICA_GM FOREIGN KEY(ID_MUSICA) REFERENCES MUSICA(ID_MUSICA)
ON UPDATE RESTRICT
ON DELETE RESTRICT;

-- RELACIONA UM ALBUM A VARIOS GENEROS MUSICAIS E UM GENRO MUSICAL PODE ESTAR PRESENTE EM VARIOS ALBUNS;
--ENTÃO O ATRIBUTO MULTIVALORADO VAI SER REPRESENTADO COMO UMA TABELA ASSOCIATIVA.
ALTER TABLE GENERO_DO_ALBUM
ADD CONSTRAINT FK_GENERO_GA FOREIGN KEY(ID_GENERO) REFERENCES GENERO_MUSICAL(ID_GENERO),
ADD CONSTRAINT FK_ALBUM_GA FOREIGN KEY(ID_ALBUM) REFERENCES ALBUM(ID_ALBUM)
ON UPDATE RESTRICT
ON DELETE RESTRICT;
